name: AuthMeSystem
version: ${project.version}
main: me.huljak.Main
api-version: 1.13
authors: [ DavidHuljak ]
description: Utility for AuthMe.
website: https://david.huljak.sk/
depend: [AuthMe]
commands:
  setspawn:

